name: JIra-SmartSheets CI/CD

on:
    push:
        branches: ["main"]

env:
    AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          cd linkex_upload_terraform
          terraform init

      # - name: Terraform Apply
      #   run: |
      #     cd linkex_upload_terraform
      #     terraform apply --auto-approve \
      #       -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
      #       -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Destroy
        run: |
          cd linkex_upload_terraform
          terraform destroy --auto-approve \
            -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
