name: JIra-SmartSheets CI/CD

on:
    push:
        branches: ["main"]

env:
    AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
            terraform init
            terraform apply --auto-approve \
                -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
                -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" 